on:
  push:
    branches:
      - master
      - main
name: Build
jobs:
  publish:
    strategy:
      matrix:
        go-version: [1.18.x]
        os:
          - ubuntu-latest
    name: Docker Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18.0' # The Go version to download (if necessary) and use.
      - name: Build docker image
        run: docker build -t tomwright/daselplayground:latest .
      - name: Docker login
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u TomWright --password-stdin
      - name: Docker tag dev
        run: docker tag tomwright/daselplayground:latest ghcr.io/tomwright/daselplayground:dev
      - name: Docker push dev
        run: docker push ghcr.io/tomwright/daselplayground:dev